name: mi_app_velneo
description: "APP DISTRITO MALLOS - Red de comerciantes con sistema de puntos"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  
  # Para cargar imágenes desde URLs remotas
  cached_network_image: ^3.4.1
  
  # HTTP requests
  http: ^1.1.0
  
  # Local storage
  shared_preferences: ^2.2.2
  
  # State management
  provider: ^6.1.1
  
  # Icons
  cupertino_icons: ^1.0.2
  
  # URL Launcher para correos y teléfonos
  url_launcher: ^6.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  
  # Assets
  assets:
    - assets/images/
    # - assets/icons/